Resources:
  HelloHandlerServiceRole11EF7C63:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: InfraStack/HelloHandler/ServiceRole/Resource
  HelloHandler2E4FBA4D:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key: e0d8573add3f52307c99d922fe49f9e4c65b3c8d7b87c892c0853455bdc11b4d.zip
      Role:
        Fn::GetAtt:
          - HelloHandlerServiceRole11EF7C63
          - Arn
      Handler: hello.handler
      Runtime: nodejs16.x
    DependsOn:
      - HelloHandlerServiceRole11EF7C63
    Metadata:
      aws:cdk:path: InfraStack/HelloHandler/Resource
      aws:asset:path: asset.e0d8573add3f52307c99d922fe49f9e4c65b3c8d7b87c892c0853455bdc11b4d
      aws:asset:is-bundled: false
      aws:asset:property: Code
  HelloHitCounterHits7AAEBF80:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: path
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: path
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: InfraStack/HelloHitCounter/Hits/Resource
  HelloHitCounterHitCounterHandlerServiceRoleD45002B8:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: InfraStack/HelloHitCounter/HitCounterHandler/ServiceRole/Resource
  HelloHitCounterHitCounterHandlerDAEA7B37:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key: e0d8573add3f52307c99d922fe49f9e4c65b3c8d7b87c892c0853455bdc11b4d.zip
      Role:
        Fn::GetAtt:
          - HelloHitCounterHitCounterHandlerServiceRoleD45002B8
          - Arn
      Environment:
        Variables:
          DOWNSTREAM_FUNCTION_NAME:
            Ref: HelloHandler2E4FBA4D
          HITS_TABLE_NAME:
            Ref: HelloHitCounterHits7AAEBF80
      Handler: hitcounter.handler
      Runtime: nodejs16.x
    DependsOn:
      - HelloHitCounterHitCounterHandlerServiceRoleD45002B8
    Metadata:
      aws:cdk:path: InfraStack/HelloHitCounter/HitCounterHandler/Resource
      aws:asset:path: asset.e0d8573add3f52307c99d922fe49f9e4c65b3c8d7b87c892c0853455bdc11b4d
      aws:asset:is-bundled: false
      aws:asset:property: Code
  HelloHttpApiACDFC6E2:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: HelloHttpApi
      ProtocolType: HTTP
    Metadata:
      aws:cdk:path: InfraStack/HelloHttpApi/Resource
  HelloHttpApiDefaultRouteHelloLambdaIntegrationF27412ED:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId:
        Ref: HelloHttpApiACDFC6E2
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::GetAtt:
          - HelloHitCounterHitCounterHandlerDAEA7B37
          - Arn
      PayloadFormatVersion: "2.0"
    Metadata:
      aws:cdk:path: InfraStack/HelloHttpApi/DefaultRoute/HelloLambdaIntegration/Resource
  HelloHttpApiDefaultRouteHelloLambdaIntegrationPermissionC8E88F96:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - HelloHitCounterHitCounterHandlerDAEA7B37
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: HelloHttpApiACDFC6E2
            - /*/*
    Metadata:
      aws:cdk:path: InfraStack/HelloHttpApi/DefaultRoute/HelloLambdaIntegration-Permission
  HelloHttpApiDefaultRoute1D186263:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: HelloHttpApiACDFC6E2
      RouteKey: $default
      AuthorizationType: NONE
      Target:
        Fn::Join:
          - ""
          - - integrations/
            - Ref: HelloHttpApiDefaultRouteHelloLambdaIntegrationF27412ED
    Metadata:
      aws:cdk:path: InfraStack/HelloHttpApi/DefaultRoute/Resource
  HelloHttpApiDefaultStageACE56ED2:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId:
        Ref: HelloHttpApiACDFC6E2
      StageName: $default
      AutoDeploy: true
    Metadata:
      aws:cdk:path: InfraStack/HelloHttpApi/DefaultStage/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/02QQW+DMAyFfwv34EKrTTuurTRtt4rtXhnisRRIEDatqoj/vgRaidN7z471PmULLxn4LMEbp5Vu0taU4L8Fq0aF0dm32JUawX+MthLjrDr+2rU/0dAZ5pAmZbADX7iW4iLqpHh3RmYShn2UkOEwVg3JAZmUvlvsnA6NP1guZ7OZFPamRqEb3q9b8GG+701cf1mhesBne+FGmc8CcU3TpOaWGIytVUHsxqFacFb+6Kw2MiNnKbb9H0KWvD9+YBN1Xf944T9F+kgRdemNbg0U8xPEOk1w4c01f4X8DfLkwsakw2jFdATFov+McCEhfQEAAA==
    Metadata:
      aws:cdk:path: InfraStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

